---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: mgmt0-master
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    docker_networks:
      - name: ice1-1
        ipam_config:
          - subnet: '10.11.0.0/16'
            gateway: '10.11.0.254'
    networks:
      - name: ice1-1
        ipv4_address: "10.11.0.1"
  - name: mgmt1-slave
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    networks:
      - name: ice1-1
        ipv4_address: "10.11.0.2"
  - name: mgmt2-slave
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    docker_networks:
      - name: ice2-1
        ipam_config:
          - subnet: '10.12.0.0/16'
            gateway: '10.12.0.254'
    networks:
      - name: ice1-1
        ipv4_address: "10.11.0.3"
      - name: ice2-1
        ipv4_address: "10.12.0.1"
  - name: mgmt3-slave
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    networks:
      - name: ice1-1
        ipv4_address: "10.11.0.4"
      - name: ice2-1
        ipv4_address: "10.12.0.2"
provisioner:
  name: ansible
  inventory:
    host_vars:
      mgmt0-master:
        j2_current_iceberg_network: ice1
        j2_node_main_network: ice1-1
        j2_node_main_network_interface: en0
        j2_management_networks:
          - ice1-1
        network_interfaces:
          - interface: en0
            ip4: 10.11.0.1
            network: ice1-1
      mgmt1-slave:
        j2_current_iceberg_network: ice1
        j2_node_main_network: ice1-1
        j2_node_main_network_interface: en0
        j2_management_networks:
          - ice1-1
        network_interfaces:
          - interface: en0
            ip4: 10.11.0.2
            network: ice1-1
      mgmt2-slave:
        j2_current_iceberg_network: ice2
        j2_node_main_network: ice2-1
        j2_node_main_network_interface: en1
        j2_management_networks:
          - ice2-1
        network_interfaces:
          - interface: en0
            ip4: 10.11.0.3
            network: ice1-1
          - interface: en1
            ip4: 10.12.0.1
            network: ice2-1
      mgmt3-slave:
        j2_current_iceberg_network: ice2
        j2_node_main_network: ice2-1
        j2_node_main_network_interface: en1
        j2_management_networks:
          - ice2-1
        network_interfaces:
          - interface: en0
            ip4: 10.11.0.4
            network: ice1-1
          - interface: en1
            ip4: 10.12.0.2
            network: ice2-1
verifier:
  name: ansible
