---
- name: Verify
  hosts: all
  tasks:
    - name: Check that files exists
      stat:
        path: "{{ item }}"
      register: stat_results
      with_items:
        - /etc/named.conf

    - name: assert files exist
      assert:
        that: "{{ item.stat.exists }}"
      loop: "{{ stat_results.results }}"

- name: Verify master DNS
  hosts: mgmt0-master
  tasks:
    - name: Check that files exists
      stat:
        path: "{{ item }}"
      register: stat_results
      with_items:
        - /var/named/forward
        - /var/named/reverse

    - name: assert files exist
      assert:
        that: "{{ item.stat.exists }}"
      loop: "{{ stat_results.results }}"
